[package]

name = "concrete-keygen"
version = "0.1.0"
edition = "2021"
build = "build.rs"
readme = "./README.md"
homepage = "https://zama.ai/"
documentation = "https://docs.zama.ai/concrete"
repository = "https://github.com/zama-ai/concrete"
license = "BSD-3-Clause-Clear"
license-file = "../../../LICENSE.txt"
description = "concrete-keygen allows you to manage keys to be used in Zama's Concrete framework. It also provides a way to manage keys in Wasm."

[[bin]]

name = "keygen"
path = "src/keygen.rs"
required-features = [ "cli" ]

[[bin]]

name = "keyasm"
path = "src/keyasm.rs"
required-features = [ "cli" ]

[lib]
name = "concrete_keygen"
path = "src/lib.rs"
crate-type = ["cdylib", "lib"]

[build-dependencies]
capnpc = "0.20.1"

[dependencies]

capnp = "0.20.3"

clap = { version = "4.5.16", features = ["derive"], optional = true }
zip = { version = "2.6.1", optional = true }

wasm-bindgen = { version = "0.2", features = ["serde-serialize"], optional = true }
wasm-bindgen-futures = { version = "0.4.50", optional = true }
web-sys = { version = "0.3.77", features = ["std", "MessagePort"], optional = true }
serde-json = { package = "serde_json", version = "1.0", optional = true }

tfhe = { version = "1.1" }
tfhe-csprng = { version = "0.5" }

[features]

default = []
cli = ["dep:zip", "dep:clap"]
wasm = ["dep:wasm-bindgen", "dep:wasm-bindgen-futures", "dep:web-sys", "dep:serde-json", "tfhe/__wasm_api"]
