[tool.poetry]
name = "hdk"
version = "0.1.0"
description = "Zama Homomorphic Development frameworK"
authors = ["Arthur Meyre <arthur.meyre@zama.ai>"]

[tool.poetry.dependencies]
python = ">=3.7,<3.10"
Sphinx = "^4.1.1"
sphinx-rtd-theme = "^0.5.2"
myst-parser = "^0.15.1"
networkx = "^2.6.1"
matplotlib = "^3.4.2"

[tool.poetry.dev-dependencies]
isort = "^5.9.2"
black = "21.7b0"
pylint = "^2.9.3"
pytest = "^6.2.4"
pytest-cov = "^2.12.1"
diff-cover = "^6.2.0"
mypy = "^0.910"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
