[tool.poetry]
name = "concretefhe"
version = "0.1.0rc3"
description = "Concrete Framework"
authors = ["Zama <hello@zama.ai>"]
packages = [
    { include = "concrete" },
]

[tool.poetry.dependencies]
python = ">=3.8,<3.9"
networkx = "^2.6.1"
matplotlib = "^3.4.2"
numpy = "^1.21.1"
pygraphviz = "^1.7"
Pillow = "^8.3.1"
loguru = "^0.5.3"

[tool.poetry.dev-dependencies]
isort = "^5.9.2"
black = "21.7b0"
pylint = "^2.9.3"
pytest = "^6.2.4"
pytest-cov = "^2.12.1"
diff-cover = "^6.2.0"
mypy = "^0.910"
pydocstyle = "^6.1.1"
jupyter = "^1.0.0"
nbmake = "^0.5"
flake8 = "^3.9.2"
flake8-bugbear = "^21.4.3"
Sphinx = "^4.1.1"
sphinx-rtd-theme = "^1.0.0"
myst-parser = "^0.15.1"
nbsphinx = "^0.8.7"
tqdm = "^4.62.2"
psutil = "^5.8.0"
py-cpuinfo = "^8.0.0"
python-dotenv = "^0.19.0"
sphinx-copybutton = "^0.4.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
filterwarnings = [
    "error"
]


