[tool.poetry]
name = "hdk"
version = "0.1.0"
description = "Zama Homomorphic Development frameworK"
authors = ["Arthur Meyre <arthur.meyre@zama.ai>"]

[tool.poetry.dependencies]
python = ">=3.6.2,<3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
