[tool.poetry]
name = "concretefhe"
version = "0.2.0-rc5"
description = "Concrete Framework"
authors = ["Zama <hello@zama.ai>"]
packages = [
    { include = "concrete" },
]

[tool.poetry.dependencies]
python = ">=3.8,<3.9"
networkx = "^2.6.3"
matplotlib = "^3.4.3"
numpy = "^1.21.2"
pygraphviz = "^1.7"
Pillow = "^8.3.2"
loguru = "^0.5.3"

[tool.poetry.dev-dependencies]
isort = "^5.9.3"
black = "^21.9b0"
pylint = "2.11.1"
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
mypy = "0.910"
pydocstyle = "^6.1.1"
jupyter = "^1.0.0"
flake8 = "^3.9.2"
flake8-bugbear = "^21.9.2"
nbsphinx = "^0.8.7"
tqdm = "^4.62.3"
psutil = "^5.8.0"
py-cpuinfo = "^8.0.0"
python-dotenv = "^0.19.0"
nbmake = "^0.9"
python-semantic-release = "7.19.2"
semver = "^2.13.0"
tomlkit = "^0.7.0"
GitPython = "^3.1.24"
pytest-xdist = "^2.4.0"
pytest-randomly = "^3.10.1"
pygments-style-tomorrow = "^1.0.0"
beautifulsoup4 = "^4.10.0"
pip-licenses = "^3.5.3"
sphinx-zama-theme = "2.0.6"
scikit-learn = "1.0.1"
pandas = "1.3.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
filterwarnings = [
    "error",
    "ignore:pandas not found, skipping conversion test.:ImportWarning",
    "ignore:scipy not found, skipping conversion test.:ImportWarning",
]

[tool.semantic_release]
version_toml = "pyproject.toml:tool.poetry.version"
version_variable = "concrete/version.py:__version__,docs/conf.py:release"
upload_to_pypi = "False"
