inputs:
  ssh_private_key:
    description: 'A ssh key to access private github repository'
    required: true

runs:
  using: "composite"
  steps:
    - name: Rust install
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Download cargo cache
      uses: Swatinem/rust-cache@v2

    # A SSH private key is required as some dependencies are from private repos
    - name: Set ssh keys
      uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ inputs.ssh_private_key }}
