name: Conformance

on:
  push:
    branches: [master, test-ci]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Format with clang-format
        run: .github/workflows/scripts/format_cpp.sh
  BuildAndTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: "KeySetCache"
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/KeySetCache
          # actions/cache does not permit to update a cache entry
          key: ${{ runner.os }}-KeySetCache-2021-12-02
          restore-keys: |
            ${{ runner.os }}-KeySetCache-

      - name: Build and test compiler
        uses: addnab/docker-run-action@v3
        with:
          registry: ghcr.io
          image: ghcr.io/zama-ai/zamalang-compiler:latest
          username: ${{ secrets.GHCR_LOGIN }}
          password: ${{ secrets.GHCR_PASSWORD }}
          options: -v ${{ github.workspace }}/compiler:/compiler -v ${{ github.workspace }}/KeySetCache:/tmp/KeySetCache
          shell: bash
          run: |
            set -e
            echo "Debug: ccache statistics (prior to the build):"
            ccache -s
            cd /compiler
            pip install pytest
            rm -rf /build
            export PYTHONPATH=""
            make CCACHE=ON BUILD_DIR=/build test
            echo "Debug: ccache statistics (after the build):"
            ccache -s
            chmod -R ugo+rwx /tmp/KeySetCache
