name: Conformance

on:
  push:
    branches: [master, test-ci]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Format with clang-format
        run: .github/workflows/scripts/format_cpp.sh
  BuildAndTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Log LLVM commit
        run: echo "LLVM commit" && cd ${{ github.workspace }}/llvm-project && git log -1

      - name: Build and test compiler
        uses: addnab/docker-run-action@v3
        with:
          registry: ghcr.io
          image: ghcr.io/zama-ai/zamalang-compiler:latest
          username: ${{ secrets.GHCR_LOGIN }}
          password: ${{ secrets.GHCR_PASSWORD }}
          options: -v ${{ github.workspace }}/compiler:/compiler
          run: |
            cd /compiler
            pip install pytest
            make BUILD_DIR=/build test
