# This job is the main jobs will dispatch build and test for every modules of our mono repo.
name: Linelint

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  linelint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Linelint
        uses: fernandrone/linelint@8136e0fa9997122d80f5f793e0bb9a45e678fbb1 # 0.0.4
        id: linelint
