name: Continuous integration - Extra tests

on:
  push:
    branches: [ main, testci ]
  pull_request:

env:
  CARGO_TERM_COLOR: always
jobs:
  check-concrete-optimizer-expensive-tests:
    runs-on: ubuntu-20.04
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v3

      - name: "Setup"
        uses: ./.github/workflows/setup
        with:
          ssh_private_key: ${{ secrets.CONCRETE_COMPILER_CI_SSH_PRIVATE }}

      - name: Tests
        run: |
          cd v0-parameters
          cargo test --release --no-fail-fast --features=expensive_tests
