name: Package Version Checker

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # At minute 0 for each hour from 8:00 to 22:00 inclusive from Monday to Friday inclusive
    # Timezone is UTC, so Paris time is +2 during the summer and +1 during winter
    - cron: '0 6-20 * * 1-5'

env:
  ACTION_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

jobs:
  check_and_notify_build:
    name: Check timestamps and notify build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97
      - name: Compare image timestamps and notify
        run: |
          ./script/actions_utils/container_timestamp_check.sh \
          --base_img_url \
          https://api.github.com/orgs/zama-ai/packages/container/zamalang-compiler/versions \
          --env_img_url \
          https://api.github.com/orgs/zama-ai/packages/container/concretefhe-env/versions \
          --token ${{ secrets.BOT_TOKEN }} \
          --org-repo ${{ github.repository }} \
          --event-type rebuild-env-docker
      - name: Send Slack Notification
        if: ${{ always() && failure() }}
        continue-on-error: true
        uses: rtCamp/action-slack-notify@12e36fc18b0689399306c2e0b3e0f2978b7f1ee7
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_ICON: https://pbs.twimg.com/profile_images/1274014582265298945/OjBKP9kn_400x400.png
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: "Package watcher finished with status ${{ job.status }} \
            (${{ env.ACTION_RUN_URL }})"
          SLACK_USERNAME: ${{ secrets.BOT_USERNAME }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
