name: Package Version Checker

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # At minute 0 for each hour from 8:00 to 22:00 inclusive from Monday to Friday inclusive
    # Timezone is UTC, so Paris time is +2 during the summer and +1 during winter
    - cron: '0 6-20 * * 1-5'

jobs:
  check_and_notify_build:
    name: Check timestamps and notify build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Compare image timestamps and notify
        run: |
          ./script/actions_utils/container_timestamp_check.sh \
          --base_img_url \
          https://api.github.com/orgs/zama-ai/packages/container/zamalang-compiler/versions \
          --env_img_url \
          https://api.github.com/orgs/zama-ai/packages/container/concretefhe-env/versions \
          --token ${{ secrets.BOT_TOKEN }} \
          --org-repo ${{ github.repository }} \
          --event-type rebuild-env-docker
