# Start all AWS build jobs on Slab CI bot.
name: Start all AWS builds

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  start-builds:
    strategy:
      matrix:
        command: [cpu-build, gpu-build, docker-images-build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Slab repo
        uses: actions/checkout@v3
        with:
          repository: zama-ai/slab
          path: slab
          token: ${{ secrets.CONCRETE_ACTIONS_TOKEN }}

      - name: Start AWS job in Slab
        shell: bash
        # TODO: step result must be correlated to HTTP return code.
        run: |
          echo -n '{"command": "${{ matrix.command }}", "git_ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}' > command.json
          SIGNATURE="$(slab/scripts/hmac_calculator.sh command.json '${{ secrets.JOB_SECRET }}')"
          curl -v -k \
          -H "Content-Type: application/json" \
          -H "X-Slab-Repository: ${{ github.repository }}" \
          -H "X-Slab-Command: start_aws" \
          -H "X-Hub-Signature-256: sha256=${SIGNATURE}" \
          -d @command.json \
          ${{ secrets.SLAB_URL }}
